version: '3.3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - db

  db:
    image: mysql:5.7.36 
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      TMPDIR: var/lib/docker/tmp
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
